name: Bug report
description: Report a problem with OmniTerm
labels: [bug]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Describe the bug and steps to reproduce.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs / Output
      description: Paste relevant logs (mask secrets).
  - type: input
    attributes:
      label: Version / Tag
      placeholder: v1.0.0 or commit SHA
