name: Feature request
description: Suggest an idea for OmniTerm
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What do you want?
      description: Describe the feature and why it helps.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed approach
      description: Outline how this could be implemented.
