name: omniterm-nightly
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package nightly zip
        run: |
          set -e
          mkdir -p dist
          ZIP="dist/omniterm-nightly.zip"
          zip -r "$ZIP" \
            kyboost bin .zshrc.kydras .tmux.conf.kydras assets \
            thunar-open-omni.action kydras-omninterm.desktop \
            kydras-omninterm-gnome.desktop kydras-omninterm-konsole.desktop \
            README.md LICENSE 2>/dev/null || true
          echo "ZIP=$ZIP" >> $GITHUB_ENV
      - name: Move/force-update 'nightly' tag on origin
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -f nightly "${GITHUB_SHA}"
          git push -f origin nightly
      - name: Create/Update GitHub Pre-release (nightly)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Nightly
          prerelease: true
          draft: false
          files: ${{ env.ZIP }}
          make_latest: false
          generate_release_notes: false
