name: omniterm-release
on:
  push:
    tags: [ 'v*' ]
permissions:
  contents: write
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package release zip
        run: |
          set -e
          TAG="${GITHUB_REF_NAME}"
          mkdir -p dist
          ZIP="dist/omniterm-${TAG}.zip"
          zip -r "$ZIP" \
            kyboost bin .zshrc.kydras .tmux.conf.kydras assets \
            thunar-open-omni.action kydras-omninterm.desktop \
            kydras-omninterm-gnome.desktop kydras-omninterm-konsole.desktop \
            README.md LICENSE 2>/dev/null || true
          sha256sum "$ZIP" > dist/SHA256SUMS.txt
          echo "ZIP=$ZIP" >> $GITHUB_ENV
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.ZIP }}
            dist/SHA256SUMS.txt
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
