name: omniterm-release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Package release zip
        run: |
          set -e
          TAG="${GITHUB_REF_NAME}"
          mkdir -p dist
          ZIP="dist/omniterm-${TAG}.zip"
          zip -r "$ZIP" \
            kyboost bin .zshrc.kydras .tmux.conf.kydras assets \
            thunar-open-omni.action kydras-omninterm.desktop \
            README.md LICENSE 2>/dev/null || true
          echo "ZIP=$ZIP" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: ${{ env.ZIP }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
