name: omniterm-release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y zsh tmux bash coreutils make debhelper zip

      - name: Build .deb package
        run: |
          make clean
          make deb
          echo "Built .deb file:"
          ls -lh dist/*.deb || true

      - name: Build zip artifact
        run: |
          mkdir -p dist
          zip -r "dist/omniterm-${GITHUB_REF_NAME}.zip" kyboost assets install.sh uninstall.sh README.md || true
          ls -lh dist/*.zip || true

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.deb
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
