name: omniterm-release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (e.g. v1.0.12)'
        required: true

permissions:
  contents: write

jobs:
  verify-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Sanity check
        run: echo "✅ Workflow structure OK — CI trigger active"
