name: omniterm-nightly
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package nightly zip
        run: |
          set -e
          mkdir -p dist
          ZIP="dist/omniterm-nightly.zip"
          zip -r "$ZIP" \
            kyboost bin .zshrc.kydras .tmux.conf.kydras assets \
            thunar-open-omni.action kydras-omninterm.desktop \
            kydras-omninterm-gnome.desktop kydras-omninterm-konsole.desktop \
            install.sh uninstall.sh scripts README.md LICENSE MINISIGN_PUBLIC_KEY.txt \
            2>/dev/null || true
          echo "ZIP=$ZIP" >> $GITHUB_ENV
          sha256sum "$ZIP" > dist/SHA256SUMS.txt
      - name: Install minisign
        run: sudo apt-get update && sudo apt-get install -y minisign
      - name: Try to restore minisign private key (optional)
        env:
          MINISIGN_SECRET_KEY: ${{ secrets.MINISIGN_SECRET_KEY }}
        run: |
          set -e
          if [ -n "$MINISIGN_SECRET_KEY" ]; then
            echo "$MINISIGN_SECRET_KEY" | base64 -d > minisign.key
            chmod 600 minisign.key
          else
            echo "MINISIGN_SECRET_KEY missing — will skip signing."
          fi
      - name: Maybe sign checksum (skips if no key)
        env:
          MINISIGN_PASSPHRASE: ${{ secrets.MINISIGN_PASSPHRASE }}
        run: |
          set -e
          if [ -f minisign.key ]; then
            minisign -S -s minisign.key -m dist/SHA256SUMS.txt -x dist/SHA256SUMS.txt.minisig -p -t "OmniTerm nightly sums" < /dev/null
          else
            echo "Skipping signing (no minisign.key)"
          fi
      - name: Move/force-update nightly tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -f nightly "${GITHUB_SHA}"
          git push -f origin nightly
      - name: Create/Update GitHub Pre-release (nightly)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Nightly
          prerelease: true
          draft: false
          files: |
            ${{ env.ZIP }}
            dist/SHA256SUMS.txt
            dist/SHA256SUMS.txt.minisig
          make_latest: false
          generate_release_notes: false
