name: release
on:
  push:
    tags: ['v*']
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (e.g. v1.2.3)'
        required: false
jobs:
  call-shared:
    uses: Kydras8/.github/.github/workflows/reusable-release.yml@main
    with:
      tag: ${{ inputs.tag }}
    secrets: inherit
